### PR TITLE
Updated Spanish translation

### PR DESCRIPTION
**Pull request by txelu**
Spanish translation completed.

### CODE REVIEW

**Comment by maniacx** [comment]
@txelu 

the pot files have been updated. 
These translation you have submitted is for a older version.
Can you please use the latest pot files?
I Apologize, i forgot to push the commit of updated pot file for translation.

**Comment by txelu** [comment]
Sure, no problem!

**Comment by txelu** [comment]
Missing changes now updated.

**Review by maniacx — APPROVED** [review]

**Comment by maniacx** [comment]
Thank you.

**Pull request merged**
